### ISSUE TITLE
How to set server side address on the local running?

### ISSUE THREAD

**Issue by zuo305** [yuvalsuede/ai-component-generator#21]
Hi I am already running it on my local by "npm run dev" or "npm run start", But every time I click the "make my day" button, it always got the "Internal Server Error" for connecting the local server, Is there one way to test on the local? Thank you very much.

**Comment by yuvalsuede** [comment]
hey, you need to set environment variables. 
You can use export OPENAI_API_KEY=<your key from open ai>

**Comment by zuo305** [comment]
Hi @yuvalsuede, Thanks for replying to me. But I am still not sure how to set the environment variables. I already add the file ".evn" and put the OPENAI_API_KEY inside. Could you give me more details about the export OPENAI_API_KEY? Thanks a lot, it is a great job.

**Comment by zuo305** [comment]
Thanks, @yuvalsuede, I figured out the problem, my account ran out of the $18... Now it is working now, exciting, hope to give some contribution in the future.
