### ISSUE TITLE
core question

### ISSUE THREAD

**Issue by zalelion** [yuvalsuede/ai-component-generator#3]
Do you use natural language or programming language? 
The answer is: programming language.

### natural language example:
```
create item component , and have options , when touch move left , show options ........  `300+ words`
```
Copy and paste but... Error & This is not what i want &  to re-describe

### programming language
```
 <ion-item-sliding>
    <ion-item>
      <ion-label>Sliding Item with End Options</ion-label>
    </ion-item>

    <ion-item-options>
      <ion-item-option>Favorite</ion-item-option>
      <ion-item-option color="danger">Delete</ion-item-option>
    </ion-item-options>
 </ion-item-sliding>
```

Yes, this is what I want.

> Natural language is not precise enough, if it were precise and abstract enough, it would already be a programming language.

> No have Strong AI ,and only  just search recognizer,

**Comment by umairabbasDev** [comment]
> Do you use natural language or programming language? The answer is: programming language.
> 
> ### natural language example:
> ```
> create item component , and have options , when touch move left , show options ........  `300+ words`
> ```
> 
> Copy and paste but... Error & This is not what i want & to re-describe
> 
> ### programming language
> ```
>  <ion-item-sliding>
>     <ion-item>
>       <ion-label>Sliding Item with End Options</ion-label>
>     </ion-item>
> 
>     <ion-item-options>
>       <ion-item-option>Favorite</ion-item-option>
>       <ion-item-option color="danger">Delete</ion-item-option>
>     </ion-item-options>
>  </ion-item-sliding>
> ```
> 
> Yes, this is what I want.
> 
> > Natural language is not precise enough, if it were precise and abstract enough, it would already be a programming language.
> 
> > No have Strong AI ,and only  just search recognizer,

Can you give me more details about what you're asking?
